### ISSUE TITLE
selamlar

### ISSUE THREAD

**Issue by canbax** [assoft/rust-crawler#1]
ben de bu şekilde 'header' vererek HTTP request ile verileri diyanetten çekmeyi denemiştim. İlk başta çalışıyor. Arka arkaya çok sık veri çekerseniz verileri vermiyor, hata veriyor https://github.com/canbax/namaz-vakti-api/blob/try-puppeteer/api/index.js onun için adhan-js kullanıp verileri kendim hesapladım ben sonradan.

**Comment by assoft** [comment]
Selamlar, 

Doğrusu bunları hobi amaçlı yapıyorum. Kendi bilgisayarımda sürekli diyanetin sitesini açıp namaz vaktine ne kadar kaldı demektense böyle küçük uygulamalar yapıyorum. 

Şu ana kadar herhangi bir problem yaşamadım. Çok yoğun istek yapılırsa sunucu geçici olarak ip adresini engelleyebilir. Bu benim için bir problem teşkil etmiyor.

**Comment by canbax** [comment]
Diyanet'in hesaplarına da çok güvenmiyorum açıkçası. [2023'te kutba yakın yerler için hesap yönetimini değiştirdiler](https://twitter.com/canbax18/status/1606594133824618497?s=20). Ayrıca verileri parsellemişler başkalarıyla paylaşmıyorlar. Onun için benim API adhan-js i kullanarak kendisi hesaplıyor.

**Comment by assoft** [comment]
Konumunuzda yaşadığınız problem gerçekten sıkıntılı. Bu gibi durumlara dikkat etmek son derece doğal bir davranış.

Biz Türkiye için böyle bir problemi hiç yaşamadık ayrıca namaz vakitleri için "semerkand takvim" kullanıyorum. Diyanetle bire bir örtüşüyor. Bizim diyanetle ilgili bir endişemiz henüz yoktur.

**Comment by canbax** [comment]
ben de Türkiye'deyim zaten. Benim güvenimi sarstı. Her bireyin kendi kararı ve sorumluluğu
